;; for some reason the tab-width can't be overriden even with this
(setq-default tab-width 4)

(require 'files)
;; tab-width when set is file-local, so add a file open hook to set the
;; tab width in every file
(add-hook 'find-file-hook '(lambda () (setq tab-width 4)))

(require 'cc-mode)
(add-hook 'c-mode-common-hook '(lambda () (setq tab-width 4)))
(require 'python)
(add-hook 'python-mode-hook '(lambda () (setq tab-width 4)))
(add-hook 'inferior-python-mode-hook '(lambda () (setq tab-width 4)))

(setq c-offsets-alist
   (quote
    ((string . c-lineup-dont-change)
     (c . c-lineup-C-comments)
     (defun-open . 0)
     (defun-close . 0)
     (defun-block-intro . +)
     (class-open . 0)
     (class-close . 0)
     (inline-open . 0)
     (inline-close . 0)
     (func-decl-cont . +)
     (knr-argdecl-intro . +)
     (knr-argdecl . 0)
     (topmost-intro . 0)
     (topmost-intro-cont . c-lineup-topmost-intro-cont)
     (annotation-top-cont . 0)
     (annotation-var-cont . +)
     (member-init-intro . +)
     (member-init-cont . c-lineup-multi-inher)
     (inher-intro . +)
     (inher-cont . c-lineup-multi-inher)
     (block-open . 0)
     (block-close . 0)
     (brace-list-open . 0)
     (brace-list-close . 0)
     (brace-list-intro . +)
     (brace-list-entry . c-lineup-under-anchor)
     (brace-entry-open . 0)
     (statement . 0)
     (statement-cont . +)
     (statement-block-intro . +)
     (statement-case-intro . +)
     (statement-case-open . +)
     (substatement . +)
     (substatement-open . 0)
     (substatement-label . 0)
     (case-label . +)
     (access-label . -)
     (label . 1)
     (do-while-closure . 0)
     (else-clause . 0)
     (catch-clause . 0)
     (comment-intro c-lineup-knr-region-comment c-lineup-comment)
     (arglist-intro . +)
     (arglist-cont c-lineup-gcc-asm-reg 0)
     (arglist-cont-nonempty c-lineup-gcc-asm-reg c-lineup-arglist)
     (arglist-close . +)
     (stream-op . c-lineup-streamop)
     (inclass . +)
     (cpp-macro . -)
     (cpp-macro-cont . +)
     (cpp-define-intro c-lineup-cpp-define +)
     (friend . 0)
     (objc-method-intro .
                        [0])
     (objc-method-args-cont . c-lineup-ObjC-method-args)
     (objc-method-call-cont c-lineup-ObjC-method-call-colons c-lineup-ObjC-method-call +)
     (extern-lang-open . 0)
     (namespace-open . 0)
     (module-open . 0)
     (composition-open . 0)
     (extern-lang-close . 0)
     (namespace-close . 0)
     (module-close . 0)
     (composition-close . 0)
     (inextern-lang . 0)
     (innamespace . +)
     (inmodule . +)
     (incomposition . +)
     (template-args-cont c-lineup-template-args +)
     (inlambda . c-lineup-inexpr-block)
     (lambda-intro-cont . +)
     (inexpr-statement . +)
     (inexpr-class . +))))
